sudo: false

matrix:
    include:
        - os: linux
          addons:
              apt:
                  packages:
                      - ghc-7.10.3
                      - cabal-install-1.22
                  sources: hvr-ghc
          before_install:
              - export PATH="/opt/ghc/7.10.3/bin:$PATH"
              - export PATH="/opt/cabal/1.22/bin:$PATH"
              - export PATH="$HOME/.cabal/bin:$PATH"

        - os: osx
          before_install:
              - brew update
              - brew install ghc cabal-install
              - export PATH="$HOME/.cabal/bin:$PATH"

install:
    - env
    - ghc --version
    - cabal --version
    - travis_retry cabal update
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure --enable-tests
    - cabal build
    - cabal test --show-details=always

cache:
    directories:
        - $HOME/.cabal
        - $HOME/.ghc
